export interface Book {
	url: string;
	key: string;
	title: string;
	author: string[];
	number_of_pages?: number;
	isbn_10?: string[];
	publishers: string[];
	publish_date?: string;
	subjects: string[];
	cover: {
		small: string;
		medium: string;
		large: string;
	};
}

export const BOOKS: Book[] = [
	{
		url: "https://openlibrary.org/books/OL7320078M/Black_Sheep",
		key: "/books/OL7320078M",
		title: "Black Sheep",
		author: ["Georgette Heyer"],
		number_of_pages: 256,
		isbn_10: ["0099850001"],
		publishers: ["Signet"],
		publish_date: "1992",
		subjects: [
			"1960s",
			"Historical",
			"History",
			"Fiction",
			"Romance",
			"Mate selection",
			"Social life and customs",
			"Maiden aunts",
			"Fiction, romance, historical",
			"Great britain, fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/78590-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/78590-M.jpg",
			large: "https://covers.openlibrary.org/b/id/78590-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL9745793M/The_Reluctant_Husband",
		key: "/books/OL9745793M",
		title: "The Reluctant Husband",
		author: ["Lynne Graham"],
		isbn_10: ["0263156524"],
		publishers: ["Harlequin Books"],
		publish_date: "October 1998",
		subjects: [
			"Romance",
			"Harlequin",
			"Fiction, romance, general",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6724700-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6724700-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6724700-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL1558080M/That_man_is_mine",
		key: "/books/OL1558080M",
		title: "That man is mine",
		author: ["Faith Baldwin"],
		number_of_pages: 369,
		isbn_10: ["1560542705"],
		publishers: ["Thorndike Press"],
		publish_date: "1992",
		subjects: ["Large type books"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8056510-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8056510-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8056510-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL5881500M/The_Nonesuch.",
		key: "/books/OL5881500M",
		title: "The Nonesuch.",
		author: ["Georgette Heyer"],
		number_of_pages: 300,
		publishers: ["Dutton"],
		publish_date: "1963",
		subjects: [
			"1960s",
			"Open Library Staff Picks",
			"Fiction",
			"Romance",
			"Historical Fiction",
			"Fiction, romance, contemporary",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6962946-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6962946-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6962946-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24939305M/Without_love",
		key: "/books/OL24939305M",
		title: "Without love",
		author: ["Jessica Steele"],
		number_of_pages: 187,
		isbn_10: ["0373029640"],
		publishers: ["Harlequin Books"],
		publish_date: "1989",
		subjects: ["Fiction, general"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6922866-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6922866-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6922866-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL10739507M/His_Bought_Mistress_(Harlequin_Presents_2439)",
		key: "/books/OL10739507M",
		title: "His Bought Mistress (Harlequin Presents # 2439)",
		author: ["Emma Darcy"],
		number_of_pages: 192,
		isbn_10: ["0373124392"],
		publishers: ["Harlequin"],
		publish_date: "January 1, 2005",
		subjects: [
			"Fiction",
			"Passion",
			"Romance",
			"Billionaires",
			"Interior decorators",
			"Fiction, romance, general",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/2407560-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/2407560-M.jpg",
			large: "https://covers.openlibrary.org/b/id/2407560-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL10739425M/His_Miracle_Baby_(Passion)",
		key: "/books/OL10739425M",
		title: "His Miracle Baby (Passion)",
		author: ["Kate Walker"],
		number_of_pages: 192,
		isbn_10: ["0373122322"],
		publishers: ["harlequin"],
		publish_date: "February 1, 2002",
		subjects: ["Romance", "Fiction", "Fiction, romance, general"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/2407479-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/2407479-M.jpg",
			large: "https://covers.openlibrary.org/b/id/2407479-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL7573271M/Faro's_Daughter",
		key: "/books/OL7573271M",
		title: "Faro's Daughter",
		author: ["Georgette Heyer"],
		number_of_pages: 272,
		isbn_10: ["0451173546"],
		publishers: ["Signet"],
		publish_date: "October 1, 1992",
		subjects: [
			"Social life and customs",
			"Fiction",
			"Romance",
			"Historical",
			"1940s",
			"Fiction, romance, regency",
			"England, fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/7378821-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/7378821-M.jpg",
			large: "https://covers.openlibrary.org/b/id/7378821-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24975286M/Fire_with_fire",
		key: "/books/OL24975286M",
		title: "Fire with fire",
		author: ["Penny Jordan"],
		number_of_pages: 189,
		isbn_10: ["0263751635"],
		publishers: ["Mills & Boon"],
		publish_date: "1985",
		subjects: [],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6893848-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6893848-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6893848-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL9745061M/The_Pleasure_King's_Bride_(Kings_Of_The_Outback)_(Harlequin_Presents_2122)",
		key: "/books/OL9745061M",
		title:
			"The Pleasure King's Bride (Kings Of The Outback) (Harlequin Presents, 2122)",
		author: ["Emma Darcy"],
		number_of_pages: 192,
		isbn_10: ["0373121229"],
		publishers: ["Harlequin Books"],
		publish_date: "August 1, 2000",
		subjects: [
			"Single mothers",
			"Pearl industry and trade",
			"Fiction",
			"Fiction, romance, general",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/214730-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/214730-M.jpg",
			large: "https://covers.openlibrary.org/b/id/214730-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL26649039M/A_secret_disgrace",
		key: "/books/OL26649039M",
		title: "A secret disgrace",
		author: ["Penny Jordan"],
		number_of_pages: 184,
		isbn_10: ["0373130716"],
		publishers: ["Harlequin Books"],
		publish_date: "2012",
		subjects: [
			"Royal houses",
			"Romance fiction",
			"Romance-language fiction",
			"Fiction",
			"Fiction, romance, general",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8413637-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8413637-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8413637-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL24751379M/The_billionaire's_bride_of_convenience",
		key: "/books/OL24751379M",
		title: "The billionaire's bride of convenience",
		author: ["Miranda Lee"],
		number_of_pages: 184,
		isbn_10: ["0373128606"],
		publishers: ["Harlequin"],
		publish_date: "2009",
		subjects: [
			"Fiction",
			"Billionaires",
			"Betrothal",
			"Sexual behavior",
			"Executives",
			"Fiction, romance, erotica",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6805126-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6805126-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6805126-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL10691327M/Distrust_Her_Shadow",
		key: "/books/OL10691327M",
		title: "Distrust Her Shadow",
		author: ["Jessica Steele"],
		number_of_pages: 189,
		isbn_10: ["0373025556"],
		publishers: ["harlequin"],
		publish_date: "May 1, 1983",
		subjects: ["Fiction, general"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/9678533-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/9678533-M.jpg",
			large: "https://covers.openlibrary.org/b/id/9678533-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL9477327M/The_Chain_of_Destiny",
		key: "/books/OL9477327M",
		title: "The Chain of Destiny",
		author: ["Betty Neels"],
		isbn_10: ["0373030533"],
		publishers: ["Harlequin"],
		publish_date: "April 1, 1990",
		subjects: ["Fiction, romance, general", "Fiction, general"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8125007-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8125007-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8125007-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL2526926M/Out_of_the_rain",
		key: "/books/OL2526926M",
		title: "Out of the rain",
		author: ["Elizabeth Cadell"],
		number_of_pages: 288,
		isbn_10: ["0896211487"],
		publishers: ["Thorndike Press"],
		publish_date: "1987",
		subjects: ["Large type books"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8097266-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8097266-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8097266-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL10241186M/Fatherhood_Fever",
		key: "/books/OL10241186M",
		title: "Fatherhood Fever",
		author: ["Emma Darcy"],
		number_of_pages: 288,
		isbn_10: ["026315937X"],
		publishers: ["Thorndike Press"],
		publish_date: "May 1999",
		subjects: ["Fiction, romance, general", "Large type books"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/9817694-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/9817694-M.jpg",
			large: "https://covers.openlibrary.org/b/id/9817694-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL8553074M/A_Perfect_Family",
		key: "/books/OL8553074M",
		title: "A Perfect Family",
		author: ["Penny Jordan"],
		number_of_pages: 378,
		isbn_10: ["1551664143"],
		publishers: ["Mira"],
		publish_date: "January 1, 1998",
		subjects: ["Fiction, general"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/771230-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/771230-M.jpg",
			large: "https://covers.openlibrary.org/b/id/771230-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL9750730M/Daughter_of_Hassan",
		key: "/books/OL9750730M",
		title: "Daughter of Hassan",
		author: ["Penny Jordan"],
		number_of_pages: 187,
		isbn_10: ["0373105371"],
		publishers: ["Harlequin Books"],
		publish_date: "October 1982",
		subjects: ["Love stories", "Fiction, general"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6485114-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6485114-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6485114-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL5950344M/Airs_above_the_ground.",
		key: "/books/OL5950344M",
		title: "Airs above the ground.",
		author: ["Mary Stewart"],
		number_of_pages: 286,
		publishers: ["M. S. Mill Co.; distributed by Morrow, New York"],
		publish_date: "1965",
		subjects: ["Fiction", "Missing persons", "Lipizzaner horse"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6627544-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6627544-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6627544-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL22430796M/Looking_for_love",
		key: "/books/OL22430796M",
		title: "Looking for love",
		author: ["Barbara Cartland"],
		number_of_pages: 220,
		isbn_10: ["075050580X"],
		publishers: ["Magna Large Print Books"],
		publish_date: "1994",
		subjects: [
			"1980s",
			"Historical Fiction",
			"Impostor Romance Fiction",
			"Sisters",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6749986-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6749986-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6749986-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL9574009M/Tempestuous_Reunion",
		key: "/books/OL9574009M",
		title: "Tempestuous Reunion",
		author: ["Lynne Graham"],
		isbn_10: ["0373115512"],
		publishers: ["Harlequin"],
		publish_date: "April 1, 1993",
		subjects: [
			"Romance",
			"Fiction",
			"Harlequin",
			"Secret child",
			"Amnesia",
			"Fiction, general",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8138244-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8138244-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8138244-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL24203501M/Claiming_his_pregnant_wife",
		key: "/books/OL24203501M",
		title: "Claiming his pregnant wife",
		author: ["Kim Lawrence"],
		number_of_pages: 184,
		isbn_10: ["037312662X"],
		publishers: ["Harlequin"],
		publish_date: "2007",
		subjects: [
			"Divorce",
			"Married people",
			"Fiction",
			"Romance",
			"Passion",
			"Pregnancy",
			"Italians",
			"Pregnancy, fiction",
			"Married people, fiction",
			"Fiction, romance, general",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6476870-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6476870-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6476870-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL9750322M/Song_Of_A_Wren_(Harlequin_Presents_No_864)",
		key: "/books/OL9750322M",
		title: "Song Of A Wren (Harlequin Presents, No 864)",
		author: ["Emma Darcy"],
		number_of_pages: 186,
		isbn_10: ["0373108648"],
		publishers: ["harlequin"],
		publish_date: "February 1, 1986",
		subjects: [],
		cover: {
			small: "https://covers.openlibrary.org/b/id/9598480-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/9598480-M.jpg",
			large: "https://covers.openlibrary.org/b/id/9598480-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL992470M/Beyond_the_stars",
		key: "/books/OL992470M",
		title: "Beyond the stars",
		author: ["Barbara Cartland"],
		number_of_pages: 158,
		isbn_10: ["0783818947"],
		publishers: ["Chivers Press", "G.K. Hall"],
		publish_date: "1997",
		subjects: [
			"Love Triangle",
			"Romance Fiction",
			"Orphans",
			"Fiction",
			"Historical Fiction",
			"1990s",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/10326542-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/10326542-M.jpg",
			large: "https://covers.openlibrary.org/b/id/10326542-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL26484264M/A_bride_for_his_majesty's_pleasure",
		key: "/books/OL26484264M",
		title: "A bride for his majesty's pleasure",
		author: ["Penny Jordan"],
		number_of_pages: 187,
		isbn_10: ["0373128762"],
		publishers: ["Harlequin"],
		publish_date: "2009",
		subjects: [
			"Sisters",
			"Brides",
			"Princes",
			"Fiction",
			"Fiction, romance, general",
			"Fiction, romance, erotica",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8227789-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8227789-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8227789-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24939174M/The_Corinthian",
		key: "/books/OL24939174M",
		title: "The Corinthian",
		author: ["Georgette Heyer"],
		number_of_pages: 215,
		isbn_10: ["0553083211"],
		publishers: ["Bantam Books"],
		publish_date: "1974",
		subjects: [
			"Open Library Staff Picks",
			"Romance",
			"Historical",
			"1940s",
			"Fiction",
			"Arranged marriage",
			"Social life and customs",
			"Nobility",
			"Young women",
			"Great britain, fiction",
			"Fiction, romance, regency",
			"Fiction, romance, contemporary",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6923778-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6923778-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6923778-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL24975352M/The_Greek_tycoon's_virgin_wife",
		key: "/books/OL24975352M",
		title: "The Greek tycoon's virgin wife",
		author: ["Helen Bianchin"],
		number_of_pages: 187,
		isbn_10: ["0373126697", "026385356X"],
		publishers: ["Harlequin"],
		publish_date: "2007",
		subjects: [
			"Socialites",
			"Greeks",
			"Fiction",
			"Virginity",
			"Arranged marriage",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6894009-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6894009-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6894009-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24422971M/Wings_on_my_heart",
		key: "/books/OL24422971M",
		title: "Wings on my heart",
		author: ["Barbara Cartland"],
		isbn_10: ["0515039047"],
		publishers: ["Pyramid Books"],
		publish_date: "1975",
		subjects: [
			"1950s",
			"Contemporary Fiction",
			"Fiction in English",
			"Love Triangle",
			"Romance Fiction",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8225197-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8225197-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8225197-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24374160M/Talk_of_the_town",
		key: "/books/OL24374160M",
		title: "Talk of the town",
		author: ["Joan Smith"],
		number_of_pages: 306,
		publishers: ["G.K. Hall"],
		publish_date: "1979",
		subjects: ["Fiction", "Romance", "Regency", "Large type books"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6616532-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6616532-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6616532-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL10739444M/The_Hired_Husband_(Wedlocked!)",
		key: "/books/OL10739444M",
		title: "The Hired Husband  (Wedlocked!)",
		author: ["Kate Walker"],
		number_of_pages: 192,
		isbn_10: ["0373122756"],
		publishers: ["Harlequin"],
		publish_date: "September 1, 2002",
		subjects: ["Fiction, romance, general"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/2407498-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/2407498-M.jpg",
			large: "https://covers.openlibrary.org/b/id/2407498-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24941148M/These_Old_Shades",
		key: "/books/OL24941148M",
		title: "These Old Shades",
		author: ["Georgette Heyer"],
		number_of_pages: 282,
		publishers: ["Bantam"],
		publish_date: "1967",
		subjects: [
			"1920s",
			"Fiction",
			"Historical",
			"Open Library Staff Picks",
			"Romance",
			"Social life and customs",
			"Fiction, romance, historical",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6920381-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6920381-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6920381-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL9698428M/The_Sheikh's_Innocent_Bride_(Harlequin_Presents)",
		key: "/books/OL9698428M",
		title: "The Sheikh's Innocent Bride (Harlequin Presents)",
		author: ["Lynne Graham"],
		number_of_pages: 192,
		isbn_10: ["0373125119"],
		publishers: ["Harlequin"],
		publish_date: "January 1, 2006",
		subjects: [
			"Man-woman relationships",
			"Brides",
			"Fiction",
			"Romance",
			"Passion",
			"Fiction, romance, general",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6615050-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6615050-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6615050-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL17390856M/Pattern_of_deceit.",
		key: "/books/OL17390856M",
		title: "Pattern of deceit.",
		author: ["Emma Darcy"],
		number_of_pages: 188,
		isbn_10: ["0263765156"],
		publishers: ["Mills & Boon"],
		publish_date: "1990",
		subjects: ["Fiction, general"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/10346679-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/10346679-M.jpg",
			large: "https://covers.openlibrary.org/b/id/10346679-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL10738561M/Positive_Approach",
		key: "/books/OL10738561M",
		title: "Positive Approach",
		author: ["Emma Darcy"],
		isbn_10: ["0373110804"],
		publishers: ["harlequin"],
		publish_date: "May 1, 1988",
		subjects: [],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6702483-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6702483-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6702483-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL10691288M/Dishonest_woman",
		key: "/books/OL10691288M",
		title: "Dishonest woman",
		author: ["Jessica Steele"],
		number_of_pages: 192,
		isbn_10: ["0373025025"],
		publishers: ["Harlequin Books"],
		publish_date: "September 1982",
		subjects: ["Fiction, general"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6490176-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6490176-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6490176-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL4744079M/Gwendolen",
		key: "/books/OL4744079M",
		title: "Gwendolen",
		author: ["Clare Darcy"],
		number_of_pages: 216,
		isbn_10: ["0802706053"],
		publishers: ["Walker"],
		publish_date: "1978",
		subjects: ["Fiction in English", "Fiction", "Large type books"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/7323589-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/7323589-M.jpg",
			large: "https://covers.openlibrary.org/b/id/7323589-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL10691855M/Bad_Neighbours",
		key: "/books/OL10691855M",
		title: "Bad Neighbours",
		author: ["Jessica Steele"],
		isbn_10: ["0373032277"],
		publishers: ["Harlequin"],
		publish_date: "September 1, 1992",
		subjects: ["Fiction, general", "Large type books"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/10504897-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/10504897-M.jpg",
			large: "https://covers.openlibrary.org/b/id/10504897-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL27915603M/The_Gabriel_Hounds",
		key: "/books/OL27915603M",
		title: "The Gabriel Hounds",
		author: ["Mary Stewart"],
		number_of_pages: 7,
		publishers: ["Fawcett Publications Inc., Fawcett World Library"],
		publish_date: "September 1968",
		subjects: [
			"The Gabriel Hounds",
			"Mary Stewart",
			"Stewart",
			"Mary",
			"10th",
			"Novel",
			"Hardcover",
			"Paperback",
			"Kindle",
			"Hodder",
			"Stoughton",
			"Coronet Book",
			"Fawcett Crest Book",
			"Suspense",
			"Mystery",
			"Historical",
			"Romance",
			"Thriller",
			"Stewart, Mary - Prose & Criticism. Internet Archive Wishlist",
			"British",
			"Women travelers",
			"Nobility",
			"Fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/9275731-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/9275731-M.jpg",
			large: "https://covers.openlibrary.org/b/id/9275731-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL10739582M/King_Of_The_Desert_Captive_Bride",
		key: "/books/OL10739582M",
		title: "King Of The Desert, Captive Bride",
		author: ["Jane Porter"],
		number_of_pages: 192,
		isbn_10: ["0373127251"],
		publishers: ["Harlequin"],
		publish_date: "May 1, 2008",
		subjects: [
			"Romance",
			"Passion",
			"Fiction",
			"Fiction, romance, general",
			"Man-woman relationships, fiction",
			"Middle east, fiction",
			"Missing persons, fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/5074022-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/5074022-M.jpg",
			large: "https://covers.openlibrary.org/b/id/5074022-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL29481001M/The_ultimate_surrender",
		key: "/books/OL29481001M",
		title: "The ultimate surrender",
		author: ["Penny Jordan"],
		isbn_10: ["0263223256"],
		publishers: ["Mills & Boon"],
		publish_date: "2011",
		subjects: ["Single mothers", "Fiction"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/10392628-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/10392628-M.jpg",
			large: "https://covers.openlibrary.org/b/id/10392628-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL29217365M/Zarif's_convenient_queen",
		key: "/books/OL29217365M",
		title: "Zarif's convenient queen",
		author: ["Lynne Graham"],
		number_of_pages: 187,
		isbn_10: ["0263242684", "026390881X"],
		publishers: ["Mills & Boon"],
		publish_date: "2014",
		subjects: [
			"Man-woman relationships",
			"Marriage",
			"Princes",
			"Fiction",
			"Fiction, romance, general",
			"Fiction, romance, erotica",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/10380457-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/10380457-M.jpg",
			large: "https://covers.openlibrary.org/b/id/10380457-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL9712634M/THE_Greek_Bridegroom",
		key: "/books/OL9712634M",
		title: "THE Greek Bridegroom",
		author: ["Helen Bianchin"],
		number_of_pages: 192,
		isbn_10: ["0373122845"],
		publishers: ["Harlequin"],
		publish_date: "November 1, 2002",
		subjects: [
			"Sexy",
			"Tycoon",
			"irresistible",
			"bruised",
			"florists",
			"Fiction, romance, general",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/214903-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/214903-M.jpg",
			large: "https://covers.openlibrary.org/b/id/214903-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL10739591M/Spanish_Billionaire_Innocent_Wife",
		key: "/books/OL10739591M",
		title: "Spanish Billionaire, Innocent Wife",
		author: ["Kate Walker"],
		number_of_pages: 192,
		isbn_10: ["0373127340"],
		publishers: ["Harlequin"],
		publish_date: "June 1, 2008",
		subjects: [
			"Large print books",
			"Fiction",
			"Romance",
			"Passion",
			"Fiction, romance, general",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/9655241-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/9655241-M.jpg",
			large: "https://covers.openlibrary.org/b/id/9655241-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL5310185M/Love_is_mine.",
		key: "/books/OL5310185M",
		title: "Love is mine.",
		author: ["Barbara Cartland"],
		number_of_pages: 287,
		isbn_10: ["0515093777"],
		publishers: ["Pyramid House"],
		publish_date: "1972",
		subjects: [
			"1950s",
			"Contemporary Fiction",
			"Fiction in English",
			"Marriage of Convenience",
			"Romance Fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6533321-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6533321-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6533321-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL3300320M/Much_ado_about_you",
		key: "/books/OL3300320M",
		title: "Much ado about you",
		author: ["Eloisa James"],
		number_of_pages: 527,
		isbn_10: ["0786274417"],
		publishers: ["Thorndike Press"],
		publish_date: "2005",
		subjects: [
			"Orphans",
			"Fiction",
			"Romance",
			"Historical Fiction",
			"Sisters",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/1472742-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/1472742-M.jpg",
			large: "https://covers.openlibrary.org/b/id/1472742-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL26472694M/The_Konstantos_marriage_demand",
		key: "/books/OL26472694M",
		title: "The Konstantos marriage demand",
		author: ["Kate Walker"],
		isbn_10: ["0263877671"],
		publishers: ["Mills & Boon"],
		publish_date: "2010",
		subjects: ["Fiction, romance, general", "Marriage, fiction"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8209016-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8209016-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8209016-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL7502924M/Watchers",
		key: "/books/OL7502924M",
		title: "Watchers",
		author: ["Dean Koontz"],
		number_of_pages: 483,
		isbn_10: ["0425107469"],
		publishers: ["Berkley"],
		publish_date: "April 1, 1988",
		subjects: [
			"Fiction",
			"Dogs",
			"Serial murders",
			"Thriller",
			"Horror stories",
			"Horror tales",
			"Genetic engineering",
			"Fiction, general",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/270391-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/270391-M.jpg",
			large: "https://covers.openlibrary.org/b/id/270391-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL29549794M/The_wealthy_Greek's_contract_wife",
		key: "/books/OL29549794M",
		title: "The wealthy Greek's contract wife",
		author: ["Penny Jordan"],
		isbn_10: ["0263229599", "0263212122"],
		publishers: ["Mills & Boon"],
		publish_date: "2011",
		subjects: ["Large type books"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/10396175-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/10396175-M.jpg",
			large: "https://covers.openlibrary.org/b/id/10396175-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL14977285M/Falcon's_prey",
		key: "/books/OL14977285M",
		title: "Falcon's prey",
		author: ["Penny Jordan"],
		number_of_pages: 188,
		isbn_10: ["0263099067"],
		publishers: ["Mills & Boon"],
		publish_date: "1981",
		subjects: [
			"1980s",
			"Contemporary Fiction",
			"Romance Fiction",
			"Fiction, romance, general",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6460263-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6460263-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6460263-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL10739555M/The_Italian's_Chosen_Wife_(Harlequin_Presents)",
		key: "/books/OL10739555M",
		title: "The Italian's Chosen Wife (Harlequin Presents)",
		author: ["Kate Hewitt"],
		number_of_pages: 192,
		isbn_10: ["0373126980"],
		publishers: ["Harlequin"],
		publish_date: "January 1, 2008",
		subjects: [
			"Waitresses",
			"Fiction",
			"Romance",
			"Passion",
			"Businessmen",
			"Marriage",
			"Italians",
			"Fiction, romance, general",
			"Italy, fiction",
			"Married people, fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/2407605-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/2407605-M.jpg",
			large: "https://covers.openlibrary.org/b/id/2407605-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL24201707M/The_billionaire's_bride_of_vengeance",
		key: "/books/OL24201707M",
		title: "The billionaire's bride of vengeance",
		author: ["Miranda Lee"],
		number_of_pages: 185,
		isbn_10: ["0373128525"],
		publishers: ["Harlequin"],
		publish_date: "2009",
		subjects: [
			"Marriage",
			"Seduction",
			"Revenge",
			"Fiction",
			"Romance",
			"Passion",
			"Billionaires",
			"Fiction, romance, erotica",
			"Man-woman relationships, fiction",
			"Fathers and daughters, fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6386298-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6386298-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6386298-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL25567645M/Bride_in_a_gilded_cage",
		key: "/books/OL25567645M",
		title: "Bride in a gilded cage",
		author: ["Abby Green"],
		number_of_pages: 186,
		isbn_10: ["0373129483"],
		publishers: ["Harlequin"],
		publish_date: "2010",
		subjects: [
			"Brides",
			"Man-woman relationships",
			"Marriage",
			"Fiction",
			"Fiction, romance, erotica",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8010200-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8010200-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8010200-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL25407655M/A_stormy_Greek_marriage",
		key: "/books/OL25407655M",
		title: "A stormy Greek marriage",
		author: ["Lynne Graham"],
		number_of_pages: 184,
		isbn_10: ["0373129572"],
		publishers: ["Harlequin"],
		publish_date: "2010",
		subjects: [
			"Greeks",
			"Single mothers",
			"Married people",
			"Fiction",
			"Birthfathers",
			"Marriage",
			"Billionaires",
			"Fiction, romance, general",
			"Marriage, fiction",
			"Greece, fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8785508-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8785508-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8785508-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL3388558M/When_he_was_wicked",
		key: "/books/OL3388558M",
		title: "When he was wicked",
		author: ["Julia Quinn"],
		number_of_pages: 368,
		isbn_10: ["0060531231"],
		publishers: ["Avon Books"],
		publish_date: "2004",
		subjects: [
			"Social life and customs",
			"Fiction",
			"Romance",
			"Historical Fiction",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/27787-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/27787-M.jpg",
			large: "https://covers.openlibrary.org/b/id/27787-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24399348M/The_love_pirate",
		key: "/books/OL24399348M",
		title: "The love pirate",
		author: ["Barbara Cartland"],
		number_of_pages: 167,
		isbn_10: ["0553112708"],
		publishers: ["Bantam Books"],
		publish_date: "1977",
		subjects: [
			"Romance Fiction",
			"American Love stories",
			"Ocean travel",
			"Open Library Staff Picks",
			"Fiction in English",
			"Fiction",
			"Women authors",
			"Historical Fiction",
			"1970s",
			"American fiction",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6656976-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6656976-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6656976-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL10739362M/Saturday'S_Bride_(Presents_2131)",
		key: "/books/OL10739362M",
		title: "Saturday'S Bride (Presents, 2131)",
		author: ["Kate Walker"],
		number_of_pages: 192,
		isbn_10: ["0373121318"],
		publishers: ["Harlequin"],
		publish_date: "September 1, 2000",
		subjects: ["Fiction, romance, general"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6718977-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6718977-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6718977-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL25974253M/The_Pregnancy_Shock",
		key: "/books/OL25974253M",
		title: "The Pregnancy Shock",
		author: ["Lynne Graham"],
		publishers: ["Harlequin Presents"],
		subjects: [
			"Administrative assistants",
			"Billionaires",
			"Greeks",
			"Single mothers",
			"Marriage",
			"Man/woman relationships",
			"Fiction",
			"Fiction, romance, general",
			"Man-woman relationships, fiction",
			"Greece, fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/7490462-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/7490462-M.jpg",
			large: "https://covers.openlibrary.org/b/id/7490462-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL25127134M/Stars_in_my_heart",
		key: "/books/OL25127134M",
		title: "Stars in my heart",
		author: ["Barbara Cartland"],
		number_of_pages: 237,
		publishers: ["Pyramid Books"],
		publish_date: "1971",
		subjects: [
			"1950s",
			"Fiction in English",
			"Historical Fiction",
			"Impostor",
			"Romance Fiction",
			"Fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6986674-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6986674-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6986674-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24229070M/Die_kleine_Heuchlerin",
		key: "/books/OL24229070M",
		title: "Die kleine Heuchlerin",
		author: ["Barbara Cartland"],
		number_of_pages: 349,
		isbn_10: ["3404102886"],
		publishers: ["Bastei Lübbe"],
		publish_date: "1984",
		subjects: [
			"1950s",
			"Fiction in English",
			"Historical Fiction",
			"Romance Fiction",
			"Fiction",
			"Impersonation",
			"History",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6492111-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6492111-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6492111-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24945103M/Out_of_reach",
		key: "/books/OL24945103M",
		title: "Out of reach",
		author: ["Barbara Cartland"],
		number_of_pages: 304,
		publishers: ["Pyramid Books"],
		publish_date: "1973",
		subjects: [
			"1940s",
			"Contemporary Fiction",
			"Disability",
			"Jealousy",
			"Romance Fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6878079-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6878079-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6878079-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL42418M/Forced_to_marry",
		key: "/books/OL42418M",
		title: "Forced to marry",
		author: ["Barbara Cartland"],
		number_of_pages: 194,
		isbn_10: ["0783887205"],
		publishers: ["G.K. Hall"],
		publish_date: "1999",
		subjects: [
			"1980s",
			"False Engagement",
			"Historical Fiction",
			"Large type books",
			"Marriage of Convenience",
			"Romance Fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/3698748-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/3698748-M.jpg",
			large: "https://covers.openlibrary.org/b/id/3698748-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL4548999M/The_sign_of_love",
		key: "/books/OL4548999M",
		title: "The sign of love",
		author: ["Barbara Cartland"],
		number_of_pages: 167,
		isbn_10: ["0872720322"],
		publishers: ["Duron Books"],
		publish_date: "1977",
		subjects: [
			"Love Triangle",
			"Romance Fiction",
			"Ocean travel",
			"Fiction in English",
			"Fiction",
			"Historical Fiction",
			"1970s",
			"Suez Canal (Egypt)",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8288830-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8288830-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8288830-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL10691511M/So_Near_So_Far",
		key: "/books/OL10691511M",
		title: "So Near, So Far",
		author: ["Jessica Steele"],
		number_of_pages: 187,
		isbn_10: ["0373028008"],
		publishers: ["Harlequin"],
		publish_date: "1 October 1986",
		subjects: ["Contemporary romance"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/9473140-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/9473140-M.jpg",
			large: "https://covers.openlibrary.org/b/id/9473140-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL7566690M/The_Virgin_and_the_Unicorn",
		key: "/books/OL7566690M",
		title: "The Virgin and the Unicorn",
		author: ["Joan Smith"],
		isbn_10: ["0449223809"],
		publishers: ["Ivy Books"],
		publish_date: "August 1, 1995",
		subjects: ["Fiction", "Regency", "Romance"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/9810671-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/9810671-M.jpg",
			large: "https://covers.openlibrary.org/b/id/9810671-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL21443720M/Touch_not_the_cat",
		key: "/books/OL21443720M",
		title: "Touch not the cat",
		author: ["Mary Stewart"],
		number_of_pages: 302,
		isbn_10: ["0449232018"],
		publishers: ["Greenwich", "Fawcett Publishers"],
		publish_date: "1976",
		subjects: [
			"Fiction in English",
			"Detective and mystery stories",
			"Romance fiction",
			"Love stories",
			"Large type books",
			"Telepathy",
			"Fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/4635824-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/4635824-M.jpg",
			large: "https://covers.openlibrary.org/b/id/4635824-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL29570875M/What_happens_in_London",
		key: "/books/OL29570875M",
		title: "What happens in London",
		author: ["Julia Quinn"],
		isbn_10: ["0749941898"],
		publishers: ["Piatkus"],
		publish_date: "2009",
		subjects: ["Social conditions", "Fiction", "History"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/10399124-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/10399124-M.jpg",
			large: "https://covers.openlibrary.org/b/id/10399124-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24237046M/The_devil_in_love",
		key: "/books/OL24237046M",
		title: "The devil in love",
		author: ["Barbara Cartland"],
		number_of_pages: 169,
		publishers: ["Bantam Books"],
		publish_date: "1975",
		subjects: [
			"1970s",
			"Fiction in English",
			"Foreign Affairs",
			"Historical Fiction",
			"Romance Fiction",
			"Fiction",
			"History",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6489482-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6489482-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6489482-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL17339989M/Bath_tangle.",
		key: "/books/OL17339989M",
		title: "Bath tangle.",
		author: ["Georgette Heyer", "Edwin Gilbert"],
		isbn_10: ["0330202375"],
		publishers: ["Pan Books in association with Heinemann"],
		publish_date: "1967",
		subjects: [
			"1950s",
			"Stepdaughters",
			"Open Library Staff Picks",
			"Stepdaughters in fiction",
			"Fiction in English",
			"Fiction",
			"Connecticut -- Fiction.",
			"Fiction, romance, regency",
			"England, fiction",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8342816-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8342816-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8342816-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL31921566M/Brighter_than_the_sun",
		key: "/books/OL31921566M",
		title: "Brighter than the sun",
		author: ["Julia Quinn"],
		number_of_pages: 355,
		isbn_10: ["1408460769", "1408460777"],
		publishers: ["Windsor/Paragon"],
		publish_date: "2010",
		subjects: ["Fiction", "Social life and customs", "Manners and customs"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/10604897-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/10604897-M.jpg",
			large: "https://covers.openlibrary.org/b/id/10604897-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL9799147M/Goddess_and_the_Gaiety_Girl",
		key: "/books/OL9799147M",
		title: "Goddess and the Gaiety Girl",
		author: ["Barbara Cartland"],
		isbn_10: ["0553142488"],
		publishers: ["Bantam Books"],
		publish_date: "October 1980",
		subjects: [
			"1980s",
			"Fiction in English",
			"Romance Fiction",
			"Historical Fiction",
			"Fiction",
			"History",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8193718-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8193718-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8193718-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL26295196M/The_sum_of_all_kisses",
		key: "/books/OL26295196M",
		title: "The sum of all kisses",
		author: ["Julia Quinn"],
		number_of_pages: 373,
		isbn_10: ["0062072927", "0062253964"],
		publishers: [],
		publish_date: "2013",
		subjects: [
			"Social life and customs",
			"Mathematicians",
			"Manners and customs",
			"Nobility",
			"Fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/11120492-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/11120492-M.jpg",
			large: "https://covers.openlibrary.org/b/id/11120492-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL25077143M/Venetia",
		key: "/books/OL25077143M",
		title: "Venetia",
		author: ["Georgette Heyer"],
		publishers: ["Sourcebooks Casablanca"],
		publish_date: "2011",
		subjects: [
			"1950s",
			"Country life",
			"Family secrets",
			"Fiction",
			"Large type books",
			"Romance",
			"Single women",
			"Fiction, romance, historical",
			"Great britain, fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/7973208-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/7973208-M.jpg",
			large: "https://covers.openlibrary.org/b/id/7973208-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL15058667M/Lady_of_quality",
		key: "/books/OL15058667M",
		title: "Lady of quality",
		author: ["Georgette Heyer"],
		isbn_10: ["0525142800"],
		publishers: ["E.P. Dutton"],
		publish_date: "1972",
		subjects: [
			"1970s",
			"Fiction",
			"Historical",
			"Romance",
			"Romance fiction",
			"Love stories",
			"Fiction - Romance",
			"Romance: Regency",
			"Romance - Regency",
			"Fiction / Romance / Regency",
			"Romance - General",
			"Regency fiction",
			"History",
			"Fiction, romance, historical",
			"Great britain, fiction",
			"English fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/9503307-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/9503307-M.jpg",
			large: "https://covers.openlibrary.org/b/id/9503307-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL6247194M/Sylvester",
		key: "/books/OL6247194M",
		title: "Sylvester",
		author: ["Georgette Heyer"],
		number_of_pages: 309,
		publishers: ["Putnam"],
		publish_date: "1957",
		subjects: [
			"Regency Romance",
			"Pride and Prejudice",
			"Fiction, romance, regency",
			"England, fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/7935183-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/7935183-M.jpg",
			large: "https://covers.openlibrary.org/b/id/7935183-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24372528M/April_lady",
		key: "/books/OL24372528M",
		title: "April lady",
		author: ["Georgette Heyer"],
		number_of_pages: 221,
		publishers: ["Ace Books"],
		publish_date: "1957",
		subjects: [
			"1950s",
			"Romance fiction",
			"English Historical fiction",
			"Love stories",
			"Man-woman relationships",
			"Fiction",
			"Fiction, romance, contemporary",
			"Georgia, fiction",
			"Fiction, religious",
			"Marriage",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6611222-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6611222-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6611222-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL4469419M/Friday's_child.",
		key: "/books/OL4469419M",
		title: "Friday's child.",
		author: ["Georgette Heyer"],
		number_of_pages: 311,
		publishers: ["Putnam"],
		publish_date: "1971",
		subjects: [
			"1940s",
			"Fiction",
			"Historical",
			"History",
			"Romance",
			"Fiction, romance, historical",
			"Great britain, fiction",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6961077-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6961077-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6961077-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL23122149M/Frederica",
		key: "/books/OL23122149M",
		title: "Frederica",
		author: ["Georgette Heyer"],
		number_of_pages: 437,
		isbn_10: ["1402214766"],
		publishers: ["Sourcebooks Inc"],
		subjects: ["Regency", "Romance", "Fiction, romance, historical"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/5547297-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/5547297-M.jpg",
			large: "https://covers.openlibrary.org/b/id/5547297-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24836907M/Medical_center",
		key: "/books/OL24836907M",
		title: "Medical center",
		author: ["Faith Baldwin"],
		number_of_pages: 370,
		publishers: ["Blakiston"],
		publish_date: "1940",
		subjects: [],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6857231-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6857231-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6857231-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL10739407M/Her_Secret_Bridegroom_(Latin_Lovers)_(Presents_Latin_Lovers_2191)",
		key: "/books/OL10739407M",
		title:
			"Her Secret Bridegroom (Latin Lovers) (Presents, Latin Lovers 2191)",
		author: ["Kate Walker"],
		number_of_pages: 192,
		isbn_10: ["0373121911"],
		publishers: ["Harlequin"],
		publish_date: "July 1, 2001",
		subjects: ["Fiction, romance, general"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/2407461-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/2407461-M.jpg",
			large: "https://covers.openlibrary.org/b/id/2407461-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL29266840M/When_Da_Silva_Breaks_the_Rules",
		key: "/books/OL29266840M",
		title: "When Da Silva Breaks the Rules",
		author: ["Abby Green"],
		number_of_pages: 288,
		publishers: ["Harlequin Mills & Boon, Limited"],
		publish_date: "2014",
		subjects: [
			"Fiction, romance, erotica",
			"Actresses, fiction",
			"Man-woman relationships, fiction",
			"Italy, fiction",
			"Man-woman relationships",
			"Fiction",
			"Actresses",
			"Billionaires",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/10411060-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/10411060-M.jpg",
			large: "https://covers.openlibrary.org/b/id/10411060-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL26393774M/Moon_burning_a_children_of_the_moon_novel",
		key: "/books/OL26393774M",
		title: "Moon burning : a children of the moon novel",
		author: [],
		publishers: [],
		subjects: [],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8088996-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8088996-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8088996-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL3400408M/The_reluctant_bride",
		key: "/books/OL3400408M",
		title: "The reluctant bride",
		author: ["Barbara Cartland"],
		number_of_pages: 355,
		isbn_10: ["0786276797"],
		publishers: ["Thorndike Press"],
		publish_date: "2005",
		subjects: [
			"Love Triangle",
			"Romance Fiction",
			"Fiction in English",
			"1970s",
			"Historical Fiction",
			"Marriage of Convenience",
			"Large type books",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8137839-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8137839-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8137839-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL7816215M/A_Walk_in_the_Woods",
		key: "/books/OL7816215M",
		title: "A Walk in the Woods",
		author: ["Bill Bryson"],
		number_of_pages: 350,
		isbn_10: ["0552997021"],
		publishers: ["Black Swan"],
		publish_date: "July 1, 1998",
		subjects: ["Description and travel", "Nonfiction", "Travel"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8252419-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8252419-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8252419-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL4437309M/Aurora",
		key: "/books/OL4437309M",
		title: "Aurora",
		author: ["Joan Smith"],
		number_of_pages: 231,
		isbn_10: ["0802706517"],
		publishers: ["Walker"],
		publish_date: "1980",
		subjects: ["Fiction", "Romance", "Regency"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6631475-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6631475-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6631475-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL24371518M/Love_in_hiding",
		key: "/books/OL24371518M",
		title: "Love in hiding",
		author: ["Barbara Cartland"],
		number_of_pages: 175,
		publishers: ["Pyramid"],
		publish_date: "1969",
		subjects: [
			"1950s",
			"Fiction in English",
			"Historical Fiction",
			"Intrigue",
			"Love Triangle",
			"Romance Fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/6608314-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/6608314-M.jpg",
			large: "https://covers.openlibrary.org/b/id/6608314-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL31880744M/Perdita",
		key: "/books/OL31880744M",
		title: "Perdita",
		author: ["Joan Smith"],
		number_of_pages: 244,
		isbn_10: ["0753182947", "0753182955"],
		publishers: ["ISIS"],
		publish_date: "2009",
		subjects: ["Traveling theater", "Fiction"],
		cover: {
			small: "https://covers.openlibrary.org/b/id/10556877-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/10556877-M.jpg",
			large: "https://covers.openlibrary.org/b/id/10556877-L.jpg",
		},
	},
	{
		url:
			"https://openlibrary.org/books/OL26522858M/The_Sicilian's_unexpected_duty",
		key: "/books/OL26522858M",
		title: "The Sicilian's unexpected duty",
		author: ["Michelle Smart"],
		number_of_pages: 252,
		isbn_10: ["037313715X"],
		publishers: [],
		publish_date: "2014",
		subjects: [
			"Pregnant women",
			"Fiction",
			"Romance",
			"Sicilians",
			"Harlequin",
			"Fiction, romance, erotica",
			"Man-woman relationships, fiction",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/8266831-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/8266831-M.jpg",
			large: "https://covers.openlibrary.org/b/id/8266831-L.jpg",
		},
	},
	{
		url: "https://openlibrary.org/books/OL9776990M/A_Passionate_Surrender",
		key: "/books/OL9776990M",
		title: "A Passionate Surrender",
		author: ["Helen Bianchin"],
		number_of_pages: 192,
		isbn_10: ["0373122799"],
		publishers: ["harlequin"],
		publish_date: "October 1, 2002",
		subjects: [
			"Companionate marriage",
			"Fiction",
			"Fiction, romance, general",
			"Large type books",
			"Greeks",
			"Businessmen",
			"Businesswomen",
			"Spouses",
			"Mistresses",
			"Pregnancy",
			"Reconciliation",
		],
		cover: {
			small: "https://covers.openlibrary.org/b/id/214898-S.jpg",
			medium: "https://covers.openlibrary.org/b/id/214898-M.jpg",
			large: "https://covers.openlibrary.org/b/id/214898-L.jpg",
		},
	},
];
